version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "domain-checker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ygolxoz0frq1"
s3_prefix = "domain-checker"
region = "us-east-1"
profile = "arumon"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

